// Air Social Mission Control - Sample Data

import type { Client, TeamMember, Task, TaskTemplate } from './legacy-types';

export const TEAM_MEMBERS: TeamMember[] = [
  // Synergy Team (Blue)
  { id: 'm1', name: 'Sophie Gore', role: 'Account Manager', team: 'synergy', email: 'sophie.gore@airsocial.co.uk' },
  { id: 'm2', name: 'Jamie Ludlow', role: 'Paid Ads Manager', team: 'synergy', email: 'jamie.ludlow@airsocial.co.uk' },
  { id: 'm3', name: 'Sophie Collins', role: 'Social Media Manager', team: 'synergy', email: 'sophie.collins@airsocial.co.uk' },

  // Ignite Team (Orange)
  { id: 'm4', name: 'Chloe Taylor', role: 'Account Manager', team: 'ignite', email: 'chloe.taylor@airsocial.co.uk' },
  { id: 'm5', name: 'Dave Gibbs', role: 'Paid Ads Manager', team: 'ignite', email: 'dave.gibbs@airsocial.co.uk' },
  { id: 'm6', name: 'Jack Underwood', role: 'Social Media Manager', team: 'ignite', email: 'jack.underwood@airsocial.co.uk' },

  // Alliance Team (Purple)
  { id: 'm7', name: 'Chloe Hodgetts', role: 'Account Manager', team: 'alliance', email: 'chloe.hodgetts@airsocial.co.uk' },
  { id: 'm8', name: 'Aaron Lewis', role: 'Paid Ads Manager', team: 'alliance', email: 'aaron.lewis@airsocial.co.uk' },
  { id: 'm9', name: 'Marcus Yeatman', role: 'Social Media Manager', team: 'alliance', email: 'marcus.yeatman@airsocial.co.uk' },
];

export const CLIENTS: Client[] = [
  // Synergy clients
  { id: 'c1', name: 'Merchant & Found', team: 'synergy', status: 'active', services: ['seo', 'paid-advertising'], monthly_retainer: 3500, assigned_members: ['m1', 'm2', 'm3'], created_at: '2024-03-10T00:00:00Z', updated_at: '2024-03-10T00:00:00Z' },
  { id: 'c2', name: 'House of Poochie', team: 'synergy', status: 'active', services: ['social-media', 'paid-advertising'], monthly_retainer: 2200, assigned_members: ['m1', 'm3'], created_at: '2024-06-15T00:00:00Z', updated_at: '2024-06-15T00:00:00Z' },
  { id: 'c3', name: 'Hurlands', team: 'synergy', status: 'active', services: ['seo', 'social-media'], monthly_retainer: 2800, assigned_members: ['m1', 'm2'], created_at: '2024-01-20T00:00:00Z', updated_at: '2024-01-20T00:00:00Z' },
  { id: 'c4', name: 'High School of Glasgow', team: 'synergy', status: 'active', services: ['seo', 'paid-advertising', 'social-media'], monthly_retainer: 4200, assigned_members: ['m1', 'm2', 'm3'], created_at: '2024-09-01T00:00:00Z', updated_at: '2024-09-01T00:00:00Z' },
  { id: 'c5', name: 'Clubwise', team: 'synergy', status: 'active', services: ['paid-advertising', 'seo'], monthly_retainer: 3800, assigned_members: ['m2', 'm3'], created_at: '2023-11-05T00:00:00Z', updated_at: '2023-11-05T00:00:00Z' },
  // Ignite clients
  { id: 'c6', name: 'Newton Huxley', team: 'ignite', status: 'active', services: ['social-media', 'paid-advertising'], monthly_retainer: 3200, assigned_members: ['m4', 'm5', 'm6'], created_at: '2024-04-12T00:00:00Z', updated_at: '2024-04-12T00:00:00Z' },
  { id: 'c7', name: 'Athleticademix', team: 'ignite', status: 'active', services: ['social-media', 'seo'], monthly_retainer: 1800, assigned_members: ['m4', 'm6'], created_at: '2024-07-20T00:00:00Z', updated_at: '2024-07-20T00:00:00Z' },
  { id: 'c8', name: 'The Kings Head', team: 'ignite', status: 'active', services: ['social-media'], monthly_retainer: 1200, assigned_members: ['m4', 'm6'], created_at: '2024-05-08T00:00:00Z', updated_at: '2024-05-08T00:00:00Z' },
  { id: 'c9', name: 'Portman Dental', team: 'ignite', status: 'active', services: ['seo', 'paid-advertising', 'social-media'], monthly_retainer: 4500, assigned_members: ['m4', 'm5', 'm6'], created_at: '2023-10-15T00:00:00Z', updated_at: '2023-10-15T00:00:00Z' },
  { id: 'c10', name: 'Omega Control Solutions', team: 'ignite', status: 'active', services: ['seo', 'paid-advertising'], monthly_retainer: 2600, assigned_members: ['m5', 'm6'], created_at: '2024-08-01T00:00:00Z', updated_at: '2024-08-01T00:00:00Z' },
  // Alliance clients
  { id: 'c11', name: 'Doors of Distinction', team: 'alliance', status: 'active', services: ['seo', 'paid-advertising'], monthly_retainer: 2800, assigned_members: ['m7', 'm8'], created_at: '2024-02-18T00:00:00Z', updated_at: '2024-02-18T00:00:00Z' },
  { id: 'c12', name: 'SCC Volunteering', team: 'alliance', status: 'active', services: ['social-media'], monthly_retainer: 1500, assigned_members: ['m7', 'm9'], created_at: '2024-06-01T00:00:00Z', updated_at: '2024-06-01T00:00:00Z' },
  { id: 'c13', name: 'Owen, White & Catlin', team: 'alliance', status: 'active', services: ['seo', 'social-media', 'paid-advertising'], monthly_retainer: 5000, assigned_members: ['m7', 'm8', 'm9'], created_at: '2023-09-10T00:00:00Z', updated_at: '2023-09-10T00:00:00Z' },
  { id: 'c14', name: 'Registry Trust', team: 'alliance', status: 'active', services: ['seo', 'paid-advertising'], monthly_retainer: 3500, assigned_members: ['m8', 'm9'], created_at: '2024-04-25T00:00:00Z', updated_at: '2024-04-25T00:00:00Z' },
  { id: 'c15', name: 'Pro Event Solutions', team: 'alliance', status: 'active', services: ['social-media', 'paid-advertising'], monthly_retainer: 2200, assigned_members: ['m7', 'm8', 'm9'], created_at: '2024-10-01T00:00:00Z', updated_at: '2024-10-01T00:00:00Z' },
];

export const TASKS: Task[] = [
  // Merchant & Found (c1) - Synergy
  {
    id: 't1',
    title: 'Keyword research for Q1 campaign',
    description: 'Research high-value keywords for new product launch',
    status: 'doing',
    priority: 'P2',
    assignee: 'Jamie Ludlow',
    client_id: 'c1',
    service: 'seo',
    due_date: '2026-02-18T00:00:00Z',
    is_recurring: false,
    recurrence_rule: null,
    created_at: '2026-02-10T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
    completed_at: null,
  },
  {
    id: 't2',
    title: 'Set up Google Ads conversion tracking',
    description: null,
    status: 'todo',
    priority: 'P1',
    assignee: 'Sophie Collins',
    client_id: 'c1',
    service: 'paid-advertising',
    due_date: '2026-02-17T00:00:00Z',
    is_recurring: false,
    recurrence_rule: null,
    created_at: '2026-02-14T00:00:00Z',
    updated_at: '2026-02-14T00:00:00Z',
    completed_at: null,
  },
  {
    id: 't3',
    title: 'Monthly SEO report',
    description: 'Generate and send monthly performance report',
    status: 'todo',
    priority: 'P3',
    assignee: 'Jamie Ludlow',
    client_id: 'c1',
    service: 'seo',
    due_date: '2026-03-01T00:00:00Z',
    is_recurring: true,
    recurrence_rule: {
      frequency: 'monthly',
      interval: 1,
      day_of_month: 'first_working_day',
    },
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
    completed_at: null,
  },
  
  // Newton Huxley (c6) - Ignite
  {
    id: 't4',
    title: 'Create Instagram reels for new product line',
    description: 'Film and edit 4 reels showcasing organic skincare',
    status: 'doing',
    priority: 'P2',
    assignee: 'Dave Gibbs',
    client_id: 'c11',
    service: 'social-media',
    due_date: '2026-02-20T00:00:00Z',
    is_recurring: false,
    recurrence_rule: null,
    created_at: '2026-02-12T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
    completed_at: null,
  },
  {
    id: 't5',
    title: 'Content calendar for March',
    description: null,
    status: 'review',
    priority: 'P3',
    assignee: 'Chloe Taylor',
    client_id: 'c11',
    service: 'social-media',
    due_date: '2026-02-25T00:00:00Z',
    is_recurring: false,
    recurrence_rule: null,
    created_at: '2026-02-10T00:00:00Z',
    updated_at: '2026-02-14T00:00:00Z',
    completed_at: null,
  },
  
  // Owen, White & Catlin (c13) - Alliance
  {
    id: 't6',
    title: 'Q1 strategy review meeting',
    description: 'Prepare deck and present performance review',
    status: 'todo',
    priority: 'P1',
    assignee: 'Chloe Hodgetts',
    client_id: 'c13',
    service: 'account-management',
    due_date: '2026-02-19T10:00:00Z',
    is_recurring: false,
    recurrence_rule: null,
    created_at: '2026-02-13T00:00:00Z',
    updated_at: '2026-02-13T00:00:00Z',
    completed_at: null,
  },
  {
    id: 't7',
    title: 'LinkedIn ad campaign optimization',
    description: 'Review CTR and adjust targeting',
    status: 'doing',
    priority: 'P2',
    assignee: 'Aaron Lewis',
    client_id: 'c13',
    service: 'paid-advertising',
    due_date: '2026-02-21T00:00:00Z',
    is_recurring: false,
    recurrence_rule: null,
    created_at: '2026-02-11T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
    completed_at: null,
  },
  {
    id: 't8',
    title: 'Weekly social media posts',
    description: 'Create and schedule LinkedIn posts for next week',
    status: 'todo',
    priority: 'P3',
    assignee: 'Marcus Yeatman',
    client_id: 'c13',
    service: 'social-media',
    due_date: '2026-02-23T00:00:00Z',
    is_recurring: true,
    recurrence_rule: {
      frequency: 'weekly',
      interval: 1,
      day_of_week: 1, // Monday
    },
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
    completed_at: null,
  },
  
  // Clubwise (c5) - Synergy
  {
    id: 't9',
    title: 'Meta Ads creative refresh',
    description: 'Design new ad creatives for summer campaign',
    status: 'todo',
    priority: 'P2',
    assignee: 'Sophie Collins',
    client_id: 'c3',
    service: 'paid-advertising',
    due_date: '2026-02-24T00:00:00Z',
    is_recurring: false,
    recurrence_rule: null,
    created_at: '2026-02-14T00:00:00Z',
    updated_at: '2026-02-14T00:00:00Z',
    completed_at: null,
  },
  {
    id: 't10',
    title: 'Engagement report for January',
    description: null,
    status: 'done',
    priority: 'P3',
    assignee: 'Sophie Gore',
    client_id: 'c3',
    service: 'social-media',
    due_date: '2026-02-10T00:00:00Z',
    is_recurring: true,
    recurrence_rule: {
      frequency: 'monthly',
      interval: 1,
      day_of_month: 10,
    },
    created_at: '2026-01-20T00:00:00Z',
    updated_at: '2026-02-10T00:00:00Z',
    completed_at: '2026-02-10T14:30:00Z',
  },
  
  // Athleticademix (c7) - Ignite
  {
    id: 't11',
    title: 'Blog post: 10 Study Tips for 2026',
    description: 'Write and publish SEO-optimized blog post',
    status: 'doing',
    priority: 'P3',
    assignee: 'Jack Underwood',
    client_id: 'c3',
    service: 'seo',
    due_date: '2026-02-22T00:00:00Z',
    is_recurring: false,
    recurrence_rule: null,
    created_at: '2026-02-13T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
    completed_at: null,
  },
  {
    id: 't12',
    title: 'TikTok video series - Study Hacks',
    description: null,
    status: 'todo',
    priority: 'P2',
    assignee: 'Dave Gibbs',
    client_id: 'c3',
    service: 'social-media',
    due_date: '2026-02-26T00:00:00Z',
    is_recurring: false,
    recurrence_rule: null,
    created_at: '2026-02-14T00:00:00Z',
    updated_at: '2026-02-14T00:00:00Z',
    completed_at: null,
  },
  
  // Doors of Distinction (c11) - Alliance
  {
    id: 't13',
    title: 'Update Google My Business photos',
    description: 'Upload new gym equipment photos',
    status: 'done',
    priority: 'P4',
    assignee: 'Marcus Yeatman',
    client_id: 'c11',
    service: 'social-media',
    due_date: '2026-02-12T00:00:00Z',
    is_recurring: false,
    recurrence_rule: null,
    created_at: '2026-02-05T00:00:00Z',
    updated_at: '2026-02-12T00:00:00Z',
    completed_at: '2026-02-12T11:15:00Z',
  },
  {
    id: 't14',
    title: 'Launch March membership promotion',
    description: 'Set up Meta & Google ad campaigns',
    status: 'todo',
    priority: 'P1',
    assignee: 'Aaron Lewis',
    client_id: 'c11',
    service: 'paid-advertising',
    due_date: '2026-02-28T00:00:00Z',
    is_recurring: false,
    recurrence_rule: null,
    created_at: '2026-02-13T00:00:00Z',
    updated_at: '2026-02-13T00:00:00Z',
    completed_at: null,
  },
  
  // Hurlands (c3) - Synergy
  {
    id: 't15',
    title: 'Local SEO audit',
    description: 'Review local citations and GMB optimisation',
    status: 'review',
    priority: 'P2',
    assignee: 'Jamie Ludlow',
    client_id: 'c3',
    service: 'seo',
    due_date: '2026-02-20T00:00:00Z',
    is_recurring: false,
    recurrence_rule: null,
    created_at: '2026-02-10T00:00:00Z',
    updated_at: '2026-02-14T00:00:00Z',
    completed_at: null,
  },
  {
    id: 't16',
    title: 'Backlink outreach campaign',
    description: null,
    status: 'todo',
    priority: 'P3',
    assignee: 'Jamie Ludlow',
    client_id: 'c3',
    service: 'seo',
    due_date: '2026-02-27T00:00:00Z',
    is_recurring: false,
    recurrence_rule: null,
    created_at: '2026-02-12T00:00:00Z',
    updated_at: '2026-02-12T00:00:00Z',
    completed_at: null,
  },
  
  // The Kings Head (c8) - Ignite
  {
    id: 't17',
    title: 'Instagram Stories - Menu highlights',
    description: 'Create daily story posts for new menu items',
    status: 'doing',
    priority: 'P3',
    assignee: 'Chloe Taylor',
    client_id: 'c8',
    service: 'social-media',
    due_date: '2026-02-25T00:00:00Z',
    is_recurring: true,
    recurrence_rule: {
      frequency: 'daily',
      interval: 1,
    },
    created_at: '2026-02-15T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
    completed_at: null,
  },
  {
    id: 't18',
    title: 'Customer review response',
    description: 'Respond to all Google and Facebook reviews',
    status: 'done',
    priority: 'P4',
    assignee: 'Dave Gibbs',
    client_id: 'c8',
    service: 'social-media',
    due_date: '2026-02-15T00:00:00Z',
    is_recurring: true,
    recurrence_rule: {
      frequency: 'weekly',
      interval: 1,
      day_of_week: 5, // Friday
    },
    created_at: '2026-02-08T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
    completed_at: '2026-02-15T16:45:00Z',
  },
  
  // Additional tasks for variety
  {
    id: 't19',
    title: 'Competitor analysis report',
    description: 'Analyse top 5 competitors\' social strategy',
    status: 'todo',
    priority: 'P3',
    assignee: 'Chloe Taylor',
    client_id: 'c11',
    service: 'social-media',
    due_date: '2026-03-05T00:00:00Z',
    is_recurring: false,
    recurrence_rule: null,
    created_at: '2026-02-14T00:00:00Z',
    updated_at: '2026-02-14T00:00:00Z',
    completed_at: null,
  },
  {
    id: 't20',
    title: 'Fix broken backlinks',
    description: null,
    status: 'doing',
    priority: 'P2',
    assignee: 'Jack Underwood',
    client_id: 'c3',
    service: 'seo',
    due_date: '2026-02-19T00:00:00Z',
    is_recurring: false,
    recurrence_rule: null,
    created_at: '2026-02-13T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
    completed_at: null,
  },
  {
    id: 't21',
    title: 'A/B test ad copy variations',
    description: 'Test 3 headline variants for conversion',
    status: 'review',
    priority: 'P2',
    assignee: 'Sophie Collins',
    client_id: 'c1',
    service: 'paid-advertising',
    due_date: '2026-02-23T00:00:00Z',
    is_recurring: false,
    recurrence_rule: null,
    created_at: '2026-02-11T00:00:00Z',
    updated_at: '2026-02-14T00:00:00Z',
    completed_at: null,
  },
  {
    id: 't22',
    title: 'Update LinkedIn company page',
    description: null,
    status: 'done',
    priority: 'P4',
    assignee: 'Marcus Yeatman',
    client_id: 'c13',
    service: 'social-media',
    due_date: '2026-02-14T00:00:00Z',
    is_recurring: false,
    recurrence_rule: null,
    created_at: '2026-02-10T00:00:00Z',
    updated_at: '2026-02-14T00:00:00Z',
    completed_at: '2026-02-14T09:20:00Z',
  },
  {
    id: 't23',
    title: 'Client onboarding call',
    description: 'Initial discovery call with new client',
    status: 'done',
    priority: 'P1',
    assignee: 'Chloe Hodgetts',
    client_id: 'c13',
    service: 'account-management',
    due_date: '2026-02-11T14:00:00Z',
    is_recurring: false,
    recurrence_rule: null,
    created_at: '2026-02-08T00:00:00Z',
    updated_at: '2026-02-11T00:00:00Z',
    completed_at: '2026-02-11T14:30:00Z',
  },
  {
    id: 't24',
    title: 'Website speed optimization',
    description: 'Improve Core Web Vitals scores',
    status: 'todo',
    priority: 'P2',
    assignee: 'Jamie Ludlow',
    client_id: 'c3',
    service: 'seo',
    due_date: '2026-03-10T00:00:00Z',
    is_recurring: false,
    recurrence_rule: null,
    created_at: '2026-02-15T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
    completed_at: null,
  },
  {
    id: 't25',
    title: 'Valentine\'s Day campaign wrap-up',
    description: null,
    status: 'done',
    priority: 'P3',
    assignee: 'Aaron Lewis',
    client_id: 'c11',
    service: 'paid-advertising',
    due_date: '2026-02-15T00:00:00Z',
    is_recurring: false,
    recurrence_rule: null,
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
    completed_at: '2026-02-15T17:10:00Z',
  },
];

export const TASK_TEMPLATES: TaskTemplate[] = [
  {
    id: 'tmpl-seo-monthly',
    name: 'SEO Monthly Tasks',
    service: 'seo',
    tasks: [
      {
        title: 'Keyword research & analysis',
        description: 'Identify new keyword opportunities and track rankings',
        status: 'todo',
        priority: 'P2',
        assignee: '',
        service: 'seo',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Content audit',
        description: 'Review existing content for optimisation opportunities',
        status: 'todo',
        priority: 'P3',
        assignee: '',
        service: 'seo',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Backlink analysis',
        description: 'Check new backlinks and identify link-building opportunities',
        status: 'todo',
        priority: 'P3',
        assignee: '',
        service: 'seo',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Technical SEO check',
        description: 'Run site crawl and fix any technical issues',
        status: 'todo',
        priority: 'P2',
        assignee: '',
        service: 'seo',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Competitor analysis',
        description: 'Review competitor rankings and strategy',
        status: 'todo',
        priority: 'P3',
        assignee: '',
        service: 'seo',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Performance report',
        description: 'Generate monthly SEO performance report',
        status: 'todo',
        priority: 'P2',
        assignee: '',
        service: 'seo',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Meta descriptions update',
        description: 'Review and optimize meta descriptions for key pages',
        status: 'todo',
        priority: 'P3',
        assignee: '',
        service: 'seo',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Internal linking review',
        description: 'Optimise internal link structure',
        status: 'todo',
        priority: 'P3',
        assignee: '',
        service: 'seo',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
    ],
  },
  {
    id: 'tmpl-paid-ads-onboarding',
    name: 'Paid Ads Onboarding',
    service: 'paid-advertising',
    tasks: [
      {
        title: 'Account setup & access',
        description: 'Set up Google Ads and Meta accounts with proper access',
        status: 'todo',
        priority: 'P1',
        assignee: '',
        service: 'paid-advertising',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Conversion tracking implementation',
        description: 'Install tracking pixels and set up conversion events',
        status: 'todo',
        priority: 'P1',
        assignee: '',
        service: 'paid-advertising',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Audience research',
        description: 'Define target audiences and create custom audiences',
        status: 'todo',
        priority: 'P2',
        assignee: '',
        service: 'paid-advertising',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Campaign structure planning',
        description: 'Design campaign structure and ad groups',
        status: 'todo',
        priority: 'P2',
        assignee: '',
        service: 'paid-advertising',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Ad creative development',
        description: 'Create ad copy and visual assets',
        status: 'todo',
        priority: 'P2',
        assignee: '',
        service: 'paid-advertising',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Campaign launch',
        description: 'Launch initial campaigns with monitoring',
        status: 'todo',
        priority: 'P1',
        assignee: '',
        service: 'paid-advertising',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
    ],
  },
  {
    id: 'tmpl-social-weekly',
    name: 'Social Media Weekly',
    service: 'social-media',
    tasks: [
      {
        title: 'Content planning',
        description: 'Plan social media content for the week',
        status: 'todo',
        priority: 'P2',
        assignee: '',
        service: 'social-media',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Content creation',
        description: 'Create graphics and copy for scheduled posts',
        status: 'todo',
        priority: 'P2',
        assignee: '',
        service: 'social-media',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Schedule posts',
        description: 'Schedule all posts in social media tool',
        status: 'todo',
        priority: 'P2',
        assignee: '',
        service: 'social-media',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Community engagement',
        description: 'Respond to comments and messages',
        status: 'todo',
        priority: 'P3',
        assignee: '',
        service: 'social-media',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Weekly analytics review',
        description: 'Review performance metrics and insights',
        status: 'todo',
        priority: 'P3',
        assignee: '',
        service: 'social-media',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
    ],
  },
  {
    id: 'tmpl-account-monthly',
    name: 'Account Management Monthly',
    service: 'account-management',
    tasks: [
      {
        title: 'Monthly client call',
        description: 'Schedule and conduct monthly check-in call',
        status: 'todo',
        priority: 'P1',
        assignee: '',
        service: 'account-management',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Performance report preparation',
        description: 'Compile data and create monthly report',
        status: 'todo',
        priority: 'P2',
        assignee: '',
        service: 'account-management',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Send monthly report',
        description: 'Email report to client with key insights',
        status: 'todo',
        priority: 'P2',
        assignee: '',
        service: 'account-management',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Next month planning',
        description: 'Plan activities and campaigns for next month',
        status: 'todo',
        priority: 'P2',
        assignee: '',
        service: 'account-management',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
    ],
  },
  {
    id: 'tmpl-content-quarterly',
    name: 'Content Strategy Quarterly',
    service: 'seo',
    tasks: [
      {
        title: 'Quarterly content audit',
        description: 'Review all published content performance',
        status: 'todo',
        priority: 'P2',
        assignee: '',
        service: 'seo',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Content gap analysis',
        description: 'Identify topics and keywords to target',
        status: 'todo',
        priority: 'P2',
        assignee: '',
        service: 'seo',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Content calendar for next quarter',
        description: 'Plan content topics and publishing schedule',
        status: 'todo',
        priority: 'P2',
        assignee: '',
        service: 'seo',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
      {
        title: 'Update cornerstone content',
        description: 'Refresh and optimize top-performing pages',
        status: 'todo',
        priority: 'P3',
        assignee: '',
        service: 'seo',
        due_date: null,
        is_recurring: false,
        recurrence_rule: null,
        completed_at: null,
      },
    ],
  },
];
